import './room-details.scss';
import '../../components/header/header.js';
import '../../components/room-info-cards/room-info-cards.js';
import '../../components/room-details/room-details.js';
import '../../components/pie-chart/pie-chart.js';
import '../../components/reviews/reviews.js';
import '../../components/bullet-list/bullet-list.js';
import '../../components/booking-form/booking-form.js';
import '../../components/footer/footer.js';
