import '../../components/booking-form/booking-form.js';
import '../../components/bullet/bullet.js';
import '../../components/footer/footer.js';
import '../../components/header/Header.js';
import '../../components/pie-chart/PieChart.js';
import '../../components/reviews/reviews.js';
import '../../components/room-info-cards/RoomInfoCard.js';
import '../../components/room-details/room-details.js';
import './details.scss';
